# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-08 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(choices=[('A', 'Yellow & green'), ('B', 'Green & red'), ('C', 'Red & blue'), ('D', 'Blue & gray'), ('E', 'Gray & black')], max_length=1)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('y', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('YE', 'Yellow'), ('GE', 'Green'), ('RE', 'Red'), ('BL', 'Blue'), ('GR', 'Gray'), ('BK', 'Black')], max_length=2)),
                ('number', models.PositiveSmallIntegerField()),
                ('climbers', models.ManyToManyField(through='boulders.Climb', to='boulders.Climber')),
            ],
        ),
        migrations.AddField(
            model_name='climb',
            name='climber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boulders.Climber'),
        ),
        migrations.AddField(
            model_name='climb',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boulders.Route'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('color', 'number')]),
        ),
        migrations.AlterIndexTogether(
            name='route',
            index_together=set([('color', 'number')]),
        ),
    ]
