# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0002_auto_20170209_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Orange'), (1, 'Yellow'), (2, 'Green'), (3, 'Red'), (4, 'Blue'), (5, 'Gray'), (6, 'Black'), (7, 'Pink')]),
        ),
    ]
