# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0003_auto_20170209_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='climber',
            name='all_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climber',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='climber',
            name='category',
            field=models.CharField(choices=[('A', 'Orange & yellow'), ('B', 'Green & red'), ('C', 'Red & blue'), ('D', 'Blue & gray'), ('E', 'Gray & black')], max_length=1),
        ),
        migrations.AlterField(
            model_name='climber',
            name='routes',
            field=models.ManyToManyField(related_name='climbers', through='boulders.Climb', to='boulders.Route'),
        ),
    ]
