# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0005_auto_20170807_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='climber',
            name='elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='elo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routesnapshot',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boulders.Route'),
        ),
    ]
