# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0007_auto_20170807_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbersnapshot',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='routesnapshot',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
