# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulders', '0008_auto_20170807_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climbersnapshot',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='routesnapshot',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='climber',
            name='category',
            field=models.CharField(choices=[('A', 'Green & red'), ('B', 'Red & blue'), ('C', 'Blue & gray')], max_length=1),
        ),
    ]
